platform:ios, "9.0"

target "demoObjective" do

pod 'MJExtension', '~> 3.0.13'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'AFNetworking', '~> 3.2.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SVProgressHUD', '~> 2.2.5'
pod 'SDCycleScrollView', '~> 1.75'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'IQKeyboardManager', '~> 5.0.7'
pod 'LEEAlert', '~> 1.1.5'
pod 'Masonry', '~> 1.1.0'
pod 'iCarousel', '~> 1.8.3'

pod 'SDWebImage', '~> 5.0.6'

end
